/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PremiumProduct = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'priceTag' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PostId = IDL.Nat;
export const ProductId = IDL.Nat;
export const Reclamation = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'whatTheySell' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'helpfulCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const RegionPrice = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
export const ProductPriceRange = IDL.Record({
  'fes' : RegionPrice,
  'casablanca' : RegionPrice,
  'marrakech' : RegionPrice,
});
export const TraditionalProduct = IDL.Record({
  'seasonalVariationPercent' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'negotiationTips' : IDL.Text,
  'category' : IDL.Text,
  'priceRanges' : ProductPriceRange,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : PostId,
  'scamVotes' : IDL.Vec(IDL.Principal),
  'titre' : IDL.Text,
  'categorie' : IDL.Text,
  'content' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'ville' : IDL.Text,
  'author' : IDL.Principal,
  'experience' : IDL.Text,
  'fairDealVotes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Tip = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'helpfulCount' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'country' : IDL.Text,
  'username' : IDL.Text,
  'quizScore' : IDL.Nat,
  'name' : IDL.Text,
  'earnedBadges' : IDL.Vec(IDL.Text),
  'tipsGiven' : IDL.Nat,
  'email' : IDL.Opt(IDL.Text),
  'firstPostCreated' : IDL.Bool,
  'scamsReported' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addPremiumProduct' : IDL.Func([PremiumProduct], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [PostId],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [ProductId],
      [],
    ),
  'createReclamation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Reclamation],
      [],
    ),
  'createTip' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deletePost' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterTraditionalProducts' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(TraditionalProduct)],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllPremiumProducts' : IDL.Func([], [IDL.Vec(PremiumProduct)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReclamations' : IDL.Func([], [IDL.Vec(Reclamation)], ['query']),
  'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getAllTraditionalProducts' : IDL.Func(
      [],
      [IDL.Vec(TraditionalProduct)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getCountry' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPremiumProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PremiumProduct)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTraditionalProductById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TraditionalProduct)],
      ['query'],
    ),
  'getTraditionalProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TraditionalProduct)],
      ['query'],
    ),
  'getTraditionalProductsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TraditionalProduct)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsername' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'initializeTraditionalProducts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCountry' : IDL.Func([IDL.Text], [], []),
  'updateEmail' : IDL.Func([IDL.Text], [], []),
  'updatePost' : IDL.Func(
      [PostId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
  'voteFairDeal' : IDL.Func([IDL.Nat], [], []),
  'voteReclamationHelpful' : IDL.Func([IDL.Nat], [IDL.Opt(Reclamation)], []),
  'voteScam' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PremiumProduct = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'priceTag' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PostId = IDL.Nat;
  const ProductId = IDL.Nat;
  const Reclamation = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'whatTheySell' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'helpfulCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const RegionPrice = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
  const ProductPriceRange = IDL.Record({
    'fes' : RegionPrice,
    'casablanca' : RegionPrice,
    'marrakech' : RegionPrice,
  });
  const TraditionalProduct = IDL.Record({
    'seasonalVariationPercent' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'negotiationTips' : IDL.Text,
    'category' : IDL.Text,
    'priceRanges' : ProductPriceRange,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : PostId,
    'scamVotes' : IDL.Vec(IDL.Principal),
    'titre' : IDL.Text,
    'categorie' : IDL.Text,
    'content' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'ville' : IDL.Text,
    'author' : IDL.Principal,
    'experience' : IDL.Text,
    'fairDealVotes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Tip = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'helpfulCount' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({ 'premium' : IDL.Null, 'free' : IDL.Null });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'country' : IDL.Text,
    'username' : IDL.Text,
    'quizScore' : IDL.Nat,
    'name' : IDL.Text,
    'earnedBadges' : IDL.Vec(IDL.Text),
    'tipsGiven' : IDL.Nat,
    'email' : IDL.Opt(IDL.Text),
    'firstPostCreated' : IDL.Bool,
    'scamsReported' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addPremiumProduct' : IDL.Func([PremiumProduct], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [PostId],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [ProductId],
        [],
      ),
    'createReclamation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Reclamation],
        [],
      ),
    'createTip' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deletePost' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterTraditionalProducts' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(TraditionalProduct)],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllPremiumProducts' : IDL.Func(
        [],
        [IDL.Vec(PremiumProduct)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReclamations' : IDL.Func([], [IDL.Vec(Reclamation)], ['query']),
    'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getAllTraditionalProducts' : IDL.Func(
        [],
        [IDL.Vec(TraditionalProduct)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getCountry' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPremiumProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PremiumProduct)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTraditionalProductById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TraditionalProduct)],
        ['query'],
      ),
    'getTraditionalProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TraditionalProduct)],
        ['query'],
      ),
    'getTraditionalProductsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TraditionalProduct)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsername' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'initializeTraditionalProducts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCountry' : IDL.Func([IDL.Text], [], []),
    'updateEmail' : IDL.Func([IDL.Text], [], []),
    'updatePost' : IDL.Func(
        [PostId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
    'voteFairDeal' : IDL.Func([IDL.Nat], [], []),
    'voteReclamationHelpful' : IDL.Func([IDL.Nat], [IDL.Opt(Reclamation)], []),
    'voteScam' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };