/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : PostId,
  'scamVotes' : Array<Principal>,
  'titre' : string,
  'categorie' : string,
  'content' : string,
  'imageBlob' : [] | [ExternalBlob],
  'ville' : string,
  'author' : Principal,
  'experience' : string,
  'fairDealVotes' : Array<Principal>,
  'timestamp' : Time,
}
export type PostId = bigint;
export interface PremiumProduct {
  'id' : bigint,
  'title' : string,
  'imageBlob' : [] | [ExternalBlob],
  'description' : string,
  'priceTag' : string,
}
export interface Product {
  'id' : ProductId,
  'imageBlob' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'seller' : Principal,
  'category' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductPriceRange {
  'fes' : RegionPrice,
  'casablanca' : RegionPrice,
  'marrakech' : RegionPrice,
}
export interface Reclamation {
  'id' : bigint,
  'city' : string,
  'whatTheySell' : string,
  'description' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'helpfulCount' : bigint,
  'location' : string,
}
export interface RegionPrice { 'max' : bigint, 'min' : bigint }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface Tip {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'helpfulCount' : bigint,
}
export interface TraditionalProduct {
  'seasonalVariationPercent' : bigint,
  'name' : string,
  'description' : string,
  'negotiationTips' : string,
  'category' : string,
  'priceRanges' : ProductPriceRange,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'status' : UserStatus,
  'country' : string,
  'username' : string,
  'quizScore' : bigint,
  'name' : string,
  'earnedBadges' : Array<string>,
  'tipsGiven' : bigint,
  'email' : [] | [string],
  'firstPostCreated' : boolean,
  'scamsReported' : bigint,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'premium' : null } |
  { 'free' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addPremiumProduct' : ActorMethod<[PremiumProduct], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPost' : ActorMethod<
    [string, string, string, string, string, [] | [ExternalBlob]],
    PostId
  >,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, [] | [ExternalBlob]],
    ProductId
  >,
  'createReclamation' : ActorMethod<
    [string, string, string, string],
    Reclamation
  >,
  'createTip' : ActorMethod<[string], bigint>,
  'deletePost' : ActorMethod<[PostId], { 'ok' : null } | { 'err' : string }>,
  'filterTraditionalProducts' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint], [] | [string]],
    Array<TraditionalProduct>
  >,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllPremiumProducts' : ActorMethod<[], Array<PremiumProduct>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReclamations' : ActorMethod<[], Array<Reclamation>>,
  'getAllTips' : ActorMethod<[], Array<Tip>>,
  'getAllTraditionalProducts' : ActorMethod<[], Array<TraditionalProduct>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getCountry' : ActorMethod<[Principal], string>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPremiumProduct' : ActorMethod<[bigint], [] | [PremiumProduct]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTraditionalProductById' : ActorMethod<
    [bigint],
    [] | [TraditionalProduct]
  >,
  'getTraditionalProductsByCategory' : ActorMethod<
    [string],
    Array<TraditionalProduct>
  >,
  'getTraditionalProductsByRegion' : ActorMethod<
    [string],
    Array<TraditionalProduct>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsername' : ActorMethod<[Principal], string>,
  'initializeTraditionalProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCountry' : ActorMethod<[string], undefined>,
  'updateEmail' : ActorMethod<[string], undefined>,
  'updatePost' : ActorMethod<
    [PostId, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateUsername' : ActorMethod<[string], undefined>,
  'voteFairDeal' : ActorMethod<[bigint], undefined>,
  'voteReclamationHelpful' : ActorMethod<[bigint], [] | [Reclamation]>,
  'voteScam' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];